version: "2.4"
services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DATABASE
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"