version: "2.4"
services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: NInAN5t3kJo8d7I3
      POSTGRES_DB: permiles
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"